# Part of Guess the Book project by Dmitry Dereshev. MIT Licence 2019.
# https://github.com/dmitry-dereshev/guess-the-book-public

# Merges metadata generated by 01_rdf_to_csv.py 
# with the frequency table generated by 03_frequentize.py.
# Removes rows with non-existent frequency tables.

import pandas as pd

def clean_IDs(data_table):
    # replaces default index with numerals-only-index based on book ID
    data = data_table
    new_index = []
    for item in data['ID']:
        new_index.append(''.join(c for c in item if c.isdigit()))
    data.index = new_index
    data = data.drop(['ID'], axis=1)
    data.index.name = 'ID'
    return data



def merge_the_sets(path_to_book_metadata, path_to_frequency_table, output_path):
    book_metadata = pd.read_csv(path_to_book_metadata)
    freq_books = pd.read_csv(path_to_frequency_table)
    clean_meta = clean_IDs(book_metadata)
    clean_freq = clean_IDs(freq_books)
    
    joined_frames = clean_meta.join(clean_freq)
    joined_frames = joined_frames.dropna(subset=clean_freq.columns, how='all')
    joined_frames.to_csv(output_path, index="ID")


path_to_book_metadata = "where/metadata/table/is.csv"
path_to_frequency_table = "where/frequency/table/is.csv"
output_path = "where/merged/table/should/go.csv"

merge_the_sets(path_to_book_metadata, path_to_frequency_table, output_path)